FROM golang:alpine as builder

RUN apk add --no-cache \
	ca-certificates \ 
	alpine-sdk \
	tzdata

COPY . /netlify-dyndns

RUN cd /netlify-dyndns && \
	CGO_ENABLED=0 GOOS=linux go build -a .

FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /netlify-dyndns/netlify-dyndns /netlify-dyndns

ENTRYPOINT ["/netlify-dyndns"]
